# Generated by Django 2.2.4 on 2019-08-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
