# Generated by Django 2.2.4 on 2019-08-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, max_length=10000, upload_to=''),
        ),
    ]
