# Generated by Django 2.2.4 on 2019-08-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190806_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar\\Avatar.jpg', help_text='不能超过5M!', upload_to='avatar/%Y%m%d/'),
        ),
    ]
