# Generated by Django 2.2.4 on 2019-08-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190806_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/Avatar.jpg', help_text='大小请勿超过5M!', upload_to='avatar/'),
        ),
    ]
