# Generated by Django 2.2.4 on 2019-08-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190807_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(blank=True, default='avatar\\Avatar.jpg', max_length=10000),
        ),
    ]
