# Generated by Django 2.2.4 on 2019-08-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190810_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(blank=True, default='avatar\\Avatar.png', max_length=10000),
        ),
    ]
