# Generated by Django 2.2.1 on 2019-05-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='qusetion',
            new_name='question',
        ),
    ]
